### ISSUE TITLE
Adding background image to the styles

### ISSUE THREAD

**Issue by zivkaziv** [line64/landricks-components#17]
Hi,
First I must say that this repo is awesome..
Second, I'm trying to set background image on **StrongMessageBrick** component (instead of the color)

I used the example in the readme and it looks like:

CSS:
`const BASE_THEME = {
  fontFamily: 'Lato',
  baseFontSize: '18px'
};

const HEADER_BAND_THEME = {
  ...BASE_THEME,
  baseFontSize: '18px',
  backgroundColor: '#71A2B6',
  textColor: '#FFFFFF',
  primaryColor: '#FFFFFF',
  primaryContrastColor: '#71A2B6',
  objectDesign: 'square-solid',
  backgroundImage: `${background}`
};`

HTML:
` <StrongMessageBrick
            theme={ HEADER_BAND_THEME }
            messageLevel1="A beautiful message, but not so long"
            messageLevel2="A related but not so important concept, that usually is a little bit longer than the previous"
            CTAs={ <CallToAction label="sign up"/>}
            styles={styles.homePageContainer}
          />`

Any advice?

**Comment by scarmuega** [comment]
Hi @zivkaziv

- what does `${background}` point to? do you use the `url()`syntax required by css?
- could you inspect the html generated at the browser level to see what's the final style it's applying?

**Comment by zivkaziv** [comment]
Hi @scarmuega 
After playing with it a little bit I solve it by using **wrapperStyle** so now I understand my mistake..

 wrapperStyle={
              styles.homePageContainer
            }>

You can erase this issue.
Sorry and thanks
