### ISSUE TITLE
Update npm

### ISSUE THREAD

**Issue by davidroman0O** [line64/landricks-components#2]
Hi!

First, you lib is cool! 😄 
Then, it seams it need to be updated to npm. I don't have the same components from Github to NPM.

When you'll have some time, plz update it 😉 

Thx

**Comment by scarmuega** [comment]
Thanks for the heads-up @warka0
We have updated npm.
If you have any ideas for the lib, pull-requests are very welcome.

**Comment by davidroman0O** [comment]
@scarmuega Thx a lot!
Promise, i will.
