### ISSUE TITLE
Errors (oh, again him? :p)

### ISSUE THREAD

**Issue by davidroman0O** [line64/landricks-components#3]
Hi again!

I know, i'm asking too much, sry for that!
In the 0.0.5, it's seams the MainTitleBrick components disappear and the style in FeatureListBrick isn't imported. The style isn't defined.

Still something great 😄 huh

**Comment by EehMauro** [comment]
Hi!

We're in process of refactoring every component, now I just uploaded a new version, you can install it from npm.

Also, I encourage you to try this repository: [landricks-starter-kit](https://github.com/line64/landricks-starter-kit)
We'll keep uploading components examples there.

Good luck!
